# Generated by Django 3.2.4 on 2022-12-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (2, 'Archived'), (1, 'Published')], default=0),
        ),
    ]
