# Generated by Django 4.1.1 on 2022-12-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultydiscussion',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (2, 'Archived'), (1, 'Published')], default=0),
        ),
    ]
