# Generated by Django 4.1.1 on 2022-12-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_studentdiscussion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydiscussion',
            name='status',
            field=models.IntegerField(choices=[(0, 'Archived'), (2, 'Mark as Offensive'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='studentdiscussion',
            name='status',
            field=models.IntegerField(choices=[(0, 'Archived'), (2, 'Mark as Offensive'), (1, 'Published')], default=0),
        ),
    ]
