# Generated by Django 4.1.1 on 2022-12-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_alter_facultydiscussion_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydiscussion',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published'), (0, 'Archived'), (2, 'Mark as Offensive')], default=1),
        ),
        migrations.AlterField(
            model_name='studentdiscussion',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published'), (0, 'Archived'), (2, 'Mark as Offensive')], default=1),
        ),
    ]
