# Generated by Django 4.1.1 on 2022-12-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='facultyKey',
        ),
        migrations.RemoveField(
            model_name='course',
            name='studentKey',
        ),
    ]
