# Generated by Django 4.1.1 on 2022-12-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_announcement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (0, 'Archived'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (0, 'Archived'), (1, 'Published')], default=0),
        ),
    ]
