# Generated by Django 4.1.1 on 2022-12-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student_status_alter_announcement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (2, 'Archived'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (2, 'Archived'), (1, 'Published')], default=0),
        ),
    ]
