# Generated by Django 4.1.1 on 2022-12-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_student_status_assignment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (2, 'Archived'), (1, 'Published')], default=0),
        ),
    ]
